server:
  port: 7777

spring:
  profiles:
    active: default
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ncruz-dev/DI-SCDDD-microservice-config.git
          default-label: main
          clone-on-start: true
          username: ncruz-dev
          password: ${GIT_TOKEN}

eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
    prefer-ip-address: true

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://container-eureka:8761/eureka/
#      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health